### ISSUE TITLE
the geojsonPath is incomplete

### ISSUE THREAD

**Issue by whutzn** [royhobbstn/faster-dijkstra#1]
you project is great! But, there is some problem with result. The properties of the geojsonPath is right but the geometry do not have complete coordinates info. Could you check you code and give me some feedback? Thanks!

**Comment by whutzn** [comment]
I find the error code 
https://github.com/royhobbstn/geojson-dijkstra/blob/e49d752ce63328cb336a949919fd5906caa53fdd/index.js#L341
may it should be `"coordinates": geometry`

**Comment by royhobbstn** [comment]
You're absolutely right!  Sorry for the bug, the project is new and I haven't gotten around to testing it thoroughly.  I have updated the code per your suggestion and can verify that it works correctly now.  I have published version 0.0.2 on npm.  Thanks for your help!
