### ISSUE TITLE
lookup.getClosestNetworkPt

### ISSUE THREAD

**Issue by minruliao** [royhobbstn/faster-dijkstra#2]
When I clicked two points (pretty far away) along a road segment, they return me the same closest network point from lookup.getClosestNetworkPt, but there are lots of network nodes between these clicked two points,  any criteria to build road network data for Graph data?  Please advise.

**Comment by royhobbstn** [comment]
I'm not quite sure what it could be.  I can look into it this weekend when I have a bit more time, but if you could come up with a minimal reproduction, it would help immensely.  Thanks!

**Comment by minruliao** [comment]
Thanks. Attached please find is my network geojson file( please change txt
[test1.txt](https://github.com/royhobbstn/geojson-dijkstra/files/5895723/test1.txt)
 to geojson), and with the following start (-110.74279911711548,44.80319264787348) and end(-110.74181228220863,44.79612224398856 ) coordinates, which gave me the same coords1 and coords2
const coords1 = lookup.getClosestNetworkPt(-110.74279911711548,44.80319264787348);
const coords2 = lookup.getClosestNetworkPt(-110.74181228220863,44.79612224398856);

**Comment by royhobbstn** [comment]
I think I see what's going on here (please feel free to correct me if I've misinterpreted).  In your example you have a network with 2 linestrings.  Each linestring has many points on it.  You'd like to be able to route from any point on your linestrings to any other point on your linestrings.
Unfortunately, in my particular implementation, your network only has 3 nodes; the start of your first linestring, the intersection of your two linestrings, and the end of your second linestring.  So those 3 points would be the only one's you'd be able to route to/from.
To be able to convert to a network that my library could use in the way you intend, you'd have to explode your geojson into many linestrings.  Some discussion on how you might be able to achieve that can be found here:  https://gis.stackexchange.com/questions/271806/exploding-line-into-segments-using-qgis  .  If you don't have any luck with the solutions in the link, please let me know and I can probably put together a quick JS script to do the task.

**Comment by minruliao** [comment]
Thanks Daniel. Yes, I can use explode line tool in QGis to create many linestrings. But my network data is from a REST service, so I have to split the linestring programmatically. Is it ok to use the same _id in its properties for some linestrings in order to use you library?

**Comment by royhobbstn** [comment]
You'll have to map each linestring to a unique _id.  The library relies on a unique _id for each segment to be able to reconstruct the path.
